In [136]:
import pandas as pd
from readfile import read_tasect
import numpy as np

In [138]:
from criterias import overalloc, time_conflicts, undersupport, unwilling, unpreffered, testfiles
from criterias import tas_n, sect_n
from agents import mutating_agent, min_agent, min_agent_ran, add_preferred_courses
from evo import Evo

In [140]:
def add_preferred_courses(sol):
    """
    Add preferred courses to the solution matrix for each TA without conflicts.

    Parameters:
    sol (np.array): A 2D array where rows represent TAs and columns represent courses (1 if assigned, 0 if not).
    preferred_courses (dict): A dictionary mapping each TA (row index) to a list of preferred course indices (column indices).

    Returns:
    np.array: Updated solution matrix with preferred courses added where possible.
    """
    # Iterate over each TA and their preferred courses
    for ta_index, courses in enumerate(tas_n[:, 2:]):
        # Check if the TA already has an assigned course
        if not np.any(sol[ta_index, :]):  # Ensure no other courses are assigned to this TA
            for course_index in courses:
                # Assign the first available preferred course without conflict
                sol[ta_index, course_index] = 1
                break  # Stop after assigning the first preferred course

    return sol

In [141]:
tas_n[:, 2:]

array([[1, 1, 1, 1, 2, 3, 1, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 1, 1, 1, 1, 2, 2],
       [1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1],
       [1, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 3, 3, 3, 3, 2],
       [1, 2, 3, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 2],
       [3, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 3, 2, 2, 1, 1],
       [1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1],
       [2, 2, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 3, 1, 1],
       [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3],
       [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 1, 1],
       [1, 2, 3, 2, 2, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1],
       [3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,

In [142]:
sect_n

array([[ 0,  0,  3,  4],
       [ 1,  1,  3,  4],
       [ 2,  1,  2,  3],
       [ 3,  1,  2,  3],
       [ 4,  2,  3,  4],
       [ 5,  2,  3,  4],
       [ 6,  3,  2,  3],
       [ 7,  3,  2,  3],
       [ 8,  3,  3,  4],
       [ 9,  4,  3,  4],
       [10,  5,  2,  3],
       [11,  5,  3,  4],
       [12,  0,  2,  3],
       [13,  0,  2,  3],
       [14,  0,  2,  3],
       [15,  6,  3,  4],
       [16,  6,  3,  4]], dtype=int64)

In [139]:
sol = np.array([[0,0],[0,0]])

In [134]:
a = min_agent_ran([sol, sol])
a

1


array([[0, 0],
       [1, 0]])